# Generated by Django 2.1.7 on 2019-03-16 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_location', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 3, 16, 13, 42, 29, 60890, tzinfo=utc))),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
